---
- name: Wait until docker health checks are healthy or ignore it if no docker healthcheck configured
  shell: docker {% raw %} ps --format "{{.Status}}" | awk -F"[()]" '{print $2}' | awk 'NF' | sort | uniq{% endraw %}
  register: docker_healthcheck_out
  until: docker_healthcheck_out.stdout is not defined or docker_healthcheck_out.stdout == 'healthy' or docker_healthcheck_out.stdout == ''
  retries: "{{ docker_deploy_healthcheck_retries | default(20) }}"
  delay: "{{ docker_deploy_healthcheck_delay | default(omit) }}"
  when: ( docker_deploy_shell_start is defined or docker_deploy_compose_template is defined ) and ( docker_deploy_healthcheck | default(true) )
  changed_when: false # shell command don't change anything on the server
  tags: docker_deploy
