---
- name: Template docker stack
  template:
    dest: "{{ docker_deploy_base_folder }}/docker-stack.yml"
    src: "{{ docker_deploy_stack_template }}"
    backup: "{{ docker_deploy_stack_template_backup }}"
  tags: docker_deploy

- name: Install docker_stack ansible module requirements
  pip:
    name: "{{ docker_deploy_stack_pip_requirements }}"
  tags: docker_deploy
  
- name: Define docker stack state and name
  set_fact:
    _docker_deploy_stack_state: "{{ docker_deploy_stack_state | default('present') }}"
    docker_deploy_stack_state__message: "??"
  tags: always

- name: Define message if starting
  set_fact:
    docker_deploy_stack_state__message: "{{ 'Start' }}"
  when: _docker_deploy_stack_state == 'present'
  tags: always

- name: Define message if stopping
  set_fact:
    docker_deploy_stack_state__message: "{{ 'Stopping' }}"
  no_log: True
  when: _docker_deploy_stack_state == 'absent'
  tags: always

- name: "Start docker stack"
  shell: docker stack deploy {{ _docker_deploy_name }}{{ ' --prune' if docker_deploy_stack_prune is defined and docker_deploy_stack_prune else '' }} --compose-file "{{ docker_deploy_base_folder }}/docker-stack.yml"
  when: _docker_deploy_stack_state == 'present'
  # retry the deploy of the stack, because sometimes it raises some strange errors that a new deploy fixes.
  register: result_start
  until: result_start.rc == 0
  retries: 5
  delay: 10
  ignore_errors: "{{ ansible_check_mode }}"
  tags: docker_deploy
  
- name: "Stop docker stack"
  shell: docker stack rm {{ _docker_deploy_name }}
  when: _docker_deploy_stack_state == 'absent'
  register: result_stop
  until: result_stop.rc == 0
  retries: 5
  delay: 10
  ignore_errors: "{{ ansible_check_mode }}"
  tags: docker_deploy

- name: Pause for {{ docker_deploy_stack_pause_to_verify | default(15) }} seconds so previous version of the stack could stop
  pause:
    seconds: "{{ docker_deploy_stack_pause_to_verify | default(15) }}"
  tags: docker_deploy
  
- name: HealthCheck
  shell: docker stack ps {{ _docker_deploy_name }} | tail -n +2 | grep -v " \\\\_ " | egrep -v "[_-]job" | awk '{ if ( $5 != $6 ) {exit -1} }'
  retries: "{{ docker_deploy_stack_verify_retries | default(50) }}"
  delay: "{{ docker_deploy_stack_verify_delay | default(15) }}"
  register: result_healthcheck
  until: result_healthcheck.rc == 0
  when: not ansible_check_mode and _docker_deploy_stack_state == 'present'
  changed_when: False
  ignore_errors: "{{ ansible_check_mode }}"
  tags: 
    - docker_deploy
    - healthcheck
