---
- name: Get checksum for each copied file with a secret_name defined
  stat:
    path: "{{ item.dest }}"
  when: item.secret_name is defined
  with_items: "{{ ( docker_deploy_files | selectattr('service', 'in', limited_services.split(',') ) ) if limited_services is defined else docker_deploy_files }}"
  loop_control:
    label: "{{ item.dest }}"
  register: docker_deploy_files_stat_out
  tags: docker_deploy

- name: Define empty dict for docker secrets checksum
  set_fact:
    docker_deploy_secrets_checksum: {}
  tags: docker_deploy

- name: Define fact for each copied file with a `secret_name` defined with checksum
  set_fact:
    docker_deploy_secrets_checksum: "{{ docker_deploy_secrets_checksum | combine( { ( _docker_deploy_name + '_' + item.0.secret_name ): ( item.1.stat.checksum | default ( 99999999 | random | to_uuid ) | truncate(10, True, '') ) } ) }}"
  loop_control:
    label: "{{ item.0.dest }}"
  when: item.0.secret_name is defined
  with_together:
    - "{{ docker_deploy_files                  | default( [] ) }}"
    - "{{ docker_deploy_files_stat_out.results | default( [] ) }}"
  tags: docker_deploy

- name: Get checksum for each templated file with a secret_name defined
  stat:
    path: "{{ item.dest }}"
  when: item.secret_name is defined
  with_items: "{{ ( docker_deploy_templates | selectattr('service', 'in', limited_services.split(',') ) ) if limited_services is defined else docker_deploy_templates }}"
  loop_control:
    label: "{{ item.dest }}"
  register: docker_deploy_templates_stat_out
  tags: docker_deploy

- name: Define fact for each templated file secret name with checksum
  set_fact:
    docker_deploy_secrets_checksum: "{{ docker_deploy_secrets_checksum | combine( { ( _docker_deploy_name + '_' + item.0.secret_name ): ( item.1.stat.checksum | default ( 99999999 | random | to_uuid ) | truncate(10, True, '') ) } ) }}"
  loop_control:
    label: "{{ item.0.dest }}"
  when: item.0.secret_name is defined
  with_together:
    - "{{ docker_deploy_templates                  | default( [] ) }}"
    - "{{ docker_deploy_templates_stat_out.results | default( [] ) }}"
  tags: docker_deploy

- name: Deploy docker secrets
  docker_secret:
    name: "{{ _docker_deploy_name }}_{{ item.name }}_{{ item.data | checksum | truncate(10, True, '') }}"
    data: "{{ item.data | b64encode }}"
    data_is_b64: true
    state: present
    force: "{{ item.force | default(omit) }}"
    labels: "{{ item.labels | default(omit) }}"
  loop_control:
    label: "{{ item.name }}"
  loop: "{{ docker_deploy_secrets }}"
  tags: docker_deploy

- name: Define fact for each secret with a checksum
  set_fact:
    docker_deploy_secrets_checksum: "{{ docker_deploy_secrets_checksum | combine( { ( _docker_deploy_name + '_' + item.0.name ): ( item.data | checksum | truncate(10, True, '') ) } ) }}"
  loop_control:
    label: "{{ item.name }}"
  loop: "{{ docker_deploy_secrets }}"
  tags: docker_deploy

- name: Print docker secrets checksum if in verbosity mode
  debug:
    var: docker_deploy_secrets_checksum
  when: ansible_verbosity > 0
  tags: docker_deploy
