---
- name: Verify presence of variables
  fail:
    msg: You need to define at least one of 'docker_deploy_stack_template', 'docker_deploy_compose_template' or 'docker_deploy_shell_start' variable.
  when: docker_deploy_stack_template   is not defined 
    and docker_deploy_compose_template is not defined 
    and docker_deploy_shell_start      is not defined
  tags: docker_deploy

- name: Define docker deploy name variable from the docker_deploy_stack_name or from the basename of docker_deploy_base_folder folder
  set_fact:
    _docker_deploy_name: "{{ docker_deploy_stack_name | default(docker_deploy_base_folder | basename) }}"
  tags: always

- name: Create root directory
  file:
    path: "{{ docker_deploy_base_folder }}"
    state: directory
  tags: docker_deploy

- name: Git
  include_tasks: git.yml
  tags: docker_deploy

- name: Create folders
  file:
    dest: "{{ item.dest | dirname }}"
    owner: "{{ item.dir_owner|default(omit) }}"
    group: "{{ item.dir_group|default(omit) }}"
    mode: "{{ item.dir_mode | default(omit) }}"
    recurse: true
    state: directory
  loop_control:
    label: "{{ item.dest }}"
  with_items: "{{ docker_deploy_folders }}"
  tags: docker_deploy

- name: Copy files
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: "{{ item.mode | default('0644') }}"
    owner: "{{ item.owner | default('root') }}"
    group: "{{ item.group | default('root') }}"
  when: item.when | default(true) | bool
  with_items: "{{ ( docker_deploy_files | selectattr('service', 'in', limited_services.split(',') ) ) if limited_services is defined else docker_deploy_files }}"
  loop_control:
    label: "{{ item.dest }}"
  register: docker_deploy_files_out
  tags: docker_deploy

- name: Template files with src
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: "{{ item.mode | default('0644') }}"
    owner: "{{ item.owner | default('root') }}"
    group: "{{ item.group | default('root') }}"
    backup: "{{ item.backup | default(omit) }}"
  when: item.src is defined and ( item.when | default(true) | bool )
  with_items: "{{ ( docker_deploy_templates | selectattr('service', 'in', limited_services.split(',') ) ) if limited_services is defined else docker_deploy_templates }}"
  loop_control:
    label: "{{ item.dest }}"
  tags: docker_deploy

- name: Template files with src_data
  template:
    src: src_data_file.j2
    dest: "{{ item.dest }}"
    mode: "{{ item.mode | default('0644') }}"
    owner: "{{ item.owner | default('root') }}"
    group: "{{ item.group | default('root') }}"
    backup: "{{ item.backup | default(omit) }}"
  when: item.src_data is defined and ( item.when | default(true) | bool )
  with_items: "{{ ( docker_deploy_templates | selectattr('service', 'in', limited_services.split(',') ) ) if limited_services is defined else docker_deploy_templates }}"
  loop_control:
    label: "{{ item.dest }}"
  tags: docker_deploy

- include_tasks: docker_configs.yml
  tags: docker_deploy

- include_tasks: docker_secrets.yml
  tags: docker_deploy

- include_tasks: stop_old.yml
  tags: docker_deploy

- name: Deploy docker using shell directly
  include_tasks: docker_deploy_shell.yml
  when: docker_deploy_shell_start is defined or docker_deploy_shell_stop is defined or ( docker_deploy_shell | default (false) | bool )
  tags: docker_deploy

- name: Deploy docker compose
  include_tasks: docker_deploy_compose.yml
  when: docker_deploy_compose_template is defined and not ( docker_deploy_shell | default (false) | bool )
  tags: docker_deploy

- name: Deploy docker stack to swarm
  include_tasks: docker_deploy_stack.yml
  when: docker_deploy_stack_template is defined
  tags: docker_deploy

- include_tasks: docker_clean.yml
  tags: docker_deploy
