---
- name: Stop and remove old docker containers
  docker_container: 
    name: "{{ item }}"
    state: absent
  with_items: "{{ docker_containers_to_remove | default([]) }}"
  tags: docker_deploy

- name: Stop and remove old docker services
  shell: docker service rm {{ item }}
  with_items: "{{ docker_services_to_remove | default([]) }}"
  tags: docker_deploy
